language: c

env:
    global:
        - OMP_NUM_THREADS=1

cache:
    - directories:
        ~/depends/install
        ~/depends/include
        ~/depends/download
        ~/depends/src
        ~/depends/lib

before_install:
    - bash install-nbodykit.sh
    - export PATH=$HOME/miniconda/bin:$PATH
    - source activate test
    - conda install --yes gsl configobj gcc_linux-64

install:
    - cp platform-options/Options.mk.travis Options.mk
    - make

script:
    - set -e
    - make test
    - pushd examples/travis
    - python3 ../../tools/make_class_power.py paramfile.genic --extraz 82.3333 65.6667
    - mpirun -np 2 ../../genic/MP-GenIC paramfile.genic
    - mpirun -np 2 ../../gadget/MP-Gadget paramfile.gadget 1 # this starts from the IC
    - python check-results.py
    - mpirun -np 2 ../../gadget/MP-Gadget paramfile.gadget 99 #Checks the gravity force error
    - mpirun -np 2 ../../gadget/MP-Gadget paramfile.gadget 99 2
    - python ../../tools/convert_bigfile_gadget_hdf5.py --input output/PART_000 --output output
    - popd
    - set +e
