language: c

env:
    global:
        - OMP_NUM_THREADS=1

cache:
    - directories:
        - ${TRAVIS_BUILD_DIR}/depends/install
        - ${TRAVIS_BUILD_DIR}/depends/include
        - ${TRAVIS_BUILD_DIR}/depends/download
        - ${TRAVIS_BUILD_DIR}/depends/src
        - ${TRAVIS_BUILD_DIR}/depends/lib

addons:
    apt:
        packages:
            - libopenmpi-dev
            - openmpi-bin
            - libgsl0-dev

install:
    - sh bootstrap.sh
    - cp Options.mk.travis Options.mk
    - make depends
    - make

script:
    - pushd examples/travis
    - sh run.sh
    - popd
